name: Build with PyInstaller

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  # 如果有依赖文件

      - name: Generate PyInstaller spec file
        run: |
          pyi-makespec \
            --name=app \
            --onefile \
            --add-data="shared_vars.py:." \
            --add-data="plugin/:plugin" \
            --add-data="static/:static" \
            --add-data="templates/:templates" \
            app.py

      - name: Edit spec file for dynamic imports
        run: |
          # 在生成的 app.spec 中插入隐藏导入
          sed -i '/a = Analysis(/a \    hiddenimports=["plugin.notification.pg"],' app.spec

      - name: Build with PyInstaller
        run: |
          pyinstaller app.spec

      - name: Verify build
        run: |
          ls -lh dist/app  # 检查文件大小
          strings dist/app | grep "pg.py"  # 验证动态模块是否包含

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: dist/app
          retention-days: 7
