name: PyInstaller Build (Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller (Direct)
        run: |
          python buildup.py

      - name: Verify build
        run: |
          ls -lh dist/app
          strings dist/app | grep "pg.py"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-binary
          path: dist/app
          retention-days: 7
