name: Build Python Standalone Executable

on:
  workflow_dispatch:  # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 根据你的项目需要调整版本

      - name: Install Nuitka and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt  # 如果有requirements.txt

      - name: Build with Nuitka
        run: |
          python -m nuitka \
            --standalone \
            --enable-plugin=anti-bloat \
            --include-data-dir=./plugin/=plugin/ \
            --include-data-dir=./plugin/notification/templates/=plugin/notification/templates/ \
            --include-data-dir=./plugin/notification/static/=plugin/notification/static/ \
            --follow-imports \
            --output-dir=dist \
            app.py

      - name: Compress the output
        run: |
          cd dist
          tar -czvf app.tar.gz app.dist/
          mv app.tar.gz ../

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v$(date +'%Y%m%d%H%M')"  # 使用时间戳作为临时tag
          name: "Standalone Executable $(date +'%Y-%m-%d')"
          body: "Nuitka standalone build of the application"
          files: |
            app.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
