name: PyInstaller Build (Fixed)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
          
      - name: Build with PyInstaller (Direct)
        run: |
            pyinstaller \
            --name=app \
            --onefile \
            --add-data="shared_vars.py:." \
            --add-data="plugin/:plugin" \
            --add-data="static/:static" \
            --add-data="templates/:templates" \
            --hidden-import=plugin.notification.pg \
            app.py
            
            pyinstaller -F ntsub.py
            
      - name: Verify build
        run: |
          ls -lh dist/app
          strings dist/app | grep "pg.py"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux
          path: dist
          retention-days: 7
